[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"